branch-defaults:
  aws:
    environment: rails-bean-env
    group_suffix: null
global:
  application_name: InterestAtlas
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
