Topic.create(name: "Pokemon")
Topic.create(name: "Magic: The Gathering")
Topic.create(name: "Dota 2")
Topic.create(name: "Dominion Online")
Topic.create(name: "Chicago Cubs")
Topic.create(name: "Jasmine Tea")
Topic.create(name: "Eevee")
Topic.create(name: "BBQ Bacon Cheeseburger")
Topic.create(name: "Grapefruit")
Topic.create(name: "Sky Diving")
User.create(email: "",fb_id: "2")