Topic.create(name: "Pokemon")
Topic.create(name: "Magic: The Gathering")
Topic.create(name: "Dota 2")
Topic.create(name: "Dominion Online")
Topic.create(name: "Chicago Cubs")
Topic.create(name: "Jasmine Tea")
Topic.create(name: "Eevee")
Topic.create(name: "BBQ Bacon Cheeseburger")
Topic.create(name: "Grapefruit")
Topic.create(name: "Sky Diving")
User.create(email: "",fb_id: "2")
Verb.create(name:"watch")
Verb.create(name:"play")
Verb.create(name:"listen to")
Verb.create(name:"learn about")
Verb.create(name:"go to")
Verb.create(name:"I identify as")